version: '3'
services:
  google-sheet-bot:
    image: grishuchkov/google-sheet-bot:v3
    container_name: google-sheet-vk-bot
    ports:
      - 8080:8080
    env_file:
      - .env
    restart: always